language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

#Scripts to be run such as tests
before_script:
  - echo "no tests. Yes there will be tests"

# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
script:
  # Build
  - docker --version #print the version for logger. 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed lequangtin95/udagram-api-feed:v4a
  - docker tag udagram-frontend lequangtin95/udagram-frontend:local
  - docker tag udagram-api-user lequangtin95/udagram-api-user:v4a
  - docker tag udagram-reverseproxy lequangtin95/udagram-reverseproxy:v4a

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lequangtin95/udagram-api-feed:v4a
  - docker push lequangtin95/udagram-frontend:local
  - docker push lequangtin95/udagram-api-user:v4a
  - docker push lequangtin95/udagram-reverseproxy:v4a
# Do similar for other three images